# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f24380020412e0d2e5e1fb861910c4b5fcd77c58daf90909042285f593b74e1d509c198fde88e8b9aeacc248174231b7956721bb7284be55badeac9878e05fd2

test:
  secret_key_base: 5593f877040853f2afbcbdd25ad29e50714af157cff75c153a0dd23c4b8520b56f1d2e6243e4cf9d3ed0d264632015a6ddfa2523c9a2f090a8ee1ca952f8ceb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
